print('Digite 4 números para realizar somas e multiplicações')
a = (float (input('Digite o valor de "a"')))
b = (float(input('Digite o valor de "b"')))
c = (float(input('Digite o valor de "c"')))
d = (float(input('Digite o valor de "d"')))
print(f'O valor de "a" + o valor de "b" é = {a+b:.2f}')
print(f'O valor de "a" + o valor de "c" é = {a+c:.2f}')
print(f'O valor de "a" + o valor de "d" é = {a+d:.2f}')
print(f'O valor de "b" + o valor de "c" é = {b+c:.2f}')
print(f'O valor de "b" + o valor de "d" é = {b+d:.2f}')
print(f'O valor de "c" + o valor de "d" é = {c+d:.2f}')
print(f'O valor de "a" * o valor de "b" é = {a*b:.2f}')
print(f'O valor de "a" * o valor de "c" é = {a*c:.2f}')
print(f'O valor de "a" * o valor de "d" é = {a*d:.2f}')
print(f'O valor de "b" * o valor de "c" é = {b*c:.2f}')
print(f'O valor de "b" * o valor de "d" é = {b*d:.2f}')
print(f'O valor de "c" * o valor de "d" é = {c*d:.2f}')
