a = float((input('Digite um número')))
b = float((input('Digite um número')))
print(f'Soma entre os valores é = {a+b:.1f}')
print(f'Subtração entre os valores é = {a-b:.1f}')
print(f'Multiplicação entre os valores é = {a*b:.1f}')
print(f'Divisão entre os valores é = {a/b:.1f}')
